# Generated by Django 4.2 on 2023-04-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bom1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jepum_code', models.CharField(max_length=20)),
                ('seq', models.CharField(max_length=3)),
                ('level', models.CharField(max_length=2)),
                ('jaje_code', models.CharField(max_length=20)),
                ('pumname', models.CharField(max_length=50)),
                ('descript', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=10)),
                ('danwi', models.CharField(max_length=5)),
                ('soyo', models.CharField(max_length=10)),
                ('jodal', models.CharField(max_length=2)),
                ('last_update', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='bom2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jepum_code', models.CharField(max_length=20)),
                ('jaje_code', models.CharField(max_length=20)),
                ('pumname', models.CharField(max_length=50)),
                ('descript', models.CharField(max_length=50)),
                ('danwi', models.CharField(max_length=5)),
                ('soyo', models.CharField(max_length=10)),
                ('last_update', models.CharField(max_length=8)),
            ],
        ),
    ]
