# Generated by Django 4.2 on 2023-04-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_mng', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bom_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jepum_code', models.CharField(max_length=20)),
                ('seq', models.CharField(max_length=3)),
                ('level', models.CharField(max_length=2)),
                ('jaje_code', models.CharField(max_length=20)),
                ('update_date', models.CharField(max_length=8)),
                ('update_sayu', models.CharField(max_length=50)),
            ],
        ),
    ]
